version: '3.8'
services:
  sae:
    build: apache
    container_name: sae
    volumes:
      - ./storage/sae:/var/www/html
    ports:
      - 8185:80
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_DATABASE=docker
      - MYSQL_USER=tp1
      - MYSQL_PASSWORD=tp12023
      - MYSQL_ROOT_PASSWORD=admin123456
    volumes:
      - ./storage/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    restart: unless-stopped
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - 8186:80
      
  minetest:
    image: lscr.io/linuxserver/minetest:latest
    container_name: minetest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./storage/mintest:/config/.minetest
    ports:
      - 30000:30000/udp
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
